-- H2 と PostgreSQL の両方で動く書き方にそろえる。

create table player (
    id                    uuid primary key,
    created_at            timestamp not null,
    total_words_completed bigint    not null default 0,
    best_combo            integer   not null default 0,
    best_multi_word       integer   not null default 0,
    completed_four_letter boolean   not null default false,
    completed_five_letter boolean   not null default false
);

create table game (
    id                    uuid primary key,
    player_id             uuid          not null references player (id),
    status                varchar(16)   not null,
    rng_state             integer       not null,
    board                 varchar(156)  not null,
    piece_shape           varchar(1)    not null,
    piece_letters         varchar(4)    not null,
    score                 bigint        not null,
    life                  integer       not null,
    combo                 integer       not null,
    landing_count         integer       not null,
    word_count            integer       not null,
    words                 varchar(1000000) not null,
    last_landing_key      varchar(64),
    last_landing_response varchar(1000000),
    end_reason            varchar(16),
    high_score            bigint        not null default 0,
    new_high_score        boolean       not null default false,
    created_at            timestamp     not null,
    finished_at           timestamp
);

create index idx_game_player_status_finished on game (player_id, status, finished_at);
create index idx_game_player_status_score on game (player_id, status, score);

create table unlocked_achievement (
    id              bigint generated by default as identity primary key,
    player_id       uuid        not null references player (id),
    achievement_key varchar(50) not null,
    unlocked_at     timestamp   not null,
    constraint uk_unlocked_achievement_player_key unique (player_id, achievement_key)
);

create table word_log (
    id             bigint generated by default as identity primary key,
    player_id      uuid          not null references player (id),
    word           varchar(32)   not null,
    part_of_speech varchar(50)   not null,
    meaning        varchar(1000) not null,
    created_at     timestamp     not null,
    constraint uk_word_log_player_word unique (player_id, word)
);
